name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
    - name: deploy to gh-pages
      run: |
        npm i
        NODE_ENV=production npm run build
        cd dist
        git init
        git add -A
        git commit -m "🚀 Deploy id ${GITHUB_RUN_ID}"
        git push -f "https://github.com/${GITHUB_REPOSITORY}.git" master:gh-pages
